write2mmc: `petitboot is not supported`

diff --git a/files/scripts/write2mmc b/files/scripts/write2mmc
--- a/files/scripts/write2mmc
+++ b/files/scripts/write2mmc
@@ -6,9 +6,14 @@ FIN="\e[0m"
 if [ -f /etc/opt/board.txt ]; then
 	source /etc/opt/board.txt;
 else
-	echo "Missing /etc/opt/board.txt";
+	echo "Missing /etc/opt/board.txt.";
 	exit 1;
-fi 
+fi
+
+if [[ "$P_VALUE" == "p2" ]]; then
+	echo "Petitboot is not supported.";
+	exit 1;
+fi
 
 # confirm
 confirm(){
