write2mmc: `maintenance`

diff --git a/files/scripts/write2mmc b/files/scripts/write2mmc
--- a/files/scripts/write2mmc
+++ b/files/scripts/write2mmc
@@ -3,14 +3,14 @@ GRN="\e[1;32m"
 YLW="\e[1;33m"
 FIN="\e[0m"
 
-### RUN AS ROOT
-run_as_root(){
-if [ "$USER" != "root" ]; then
-        echo "Please run this as root or with sudo privileges."
-        exit 1
-fi
-}
+if [ -f /etc/opt/board.txt ]; then
+	source /etc/opt/board.txt;
+else
+	echo "Missing /etc/opt/board.txt";
+	exit 1;
+fi 
 
+# confirm
 confirm(){
 echo -e "${YLW}This script requires a internet connection."
 echo -e "If not connected to the webs, than say no${FIN} ..."
@@ -23,7 +23,7 @@ case "$choice" in
 esac
 }
 
-### PROGRESS BAR
+# progress bar
 check_progressbar(){
 DPB="sudo wget -cq https://raw.githubusercontent.com/pyavitz/bash_progress_bar/master/progress_bar.sh -P /etc/opt/"
 MPB="sudo mv -f /etc/opt/progress_bar.sh /etc/opt/progressbar.txt"
@@ -35,7 +35,7 @@ else
 fi
 }
 
-### BIND EMMC
+# bind emmc
 libre_bind_emmc(){
 echo -n d0074000.mmc > /sys/bus/platform/drivers/meson-gx-mmc/unbind
 sleep 1
@@ -60,40 +60,40 @@ sleep 1
 lsblk -dno NAME,SIZE
 }
 
-### PARTITION DRIVE
+# partition
 partition(){
 # allwinner
-if [[ `grep -w 'BOARD="nanopi"' "/etc/opt/board.txt"` ]]; then
+if [[ "$BOARD" == "nanopi" ]]; then
 	MMC="/dev/mmcblk2";
 	OFFSET="2048";
 fi
 # amlogic
-if [[ `grep -w 'BOARD="lepotato"' "/etc/opt/board.txt"` ]]; then
+if [[ "$BOARD" == "lepotato" ]]; then
 	MMC="/dev/mmcblk1";
 	OFFSET="2248";
 fi
-if [[ `grep -w 'BOARD="odroidc4"' "/etc/opt/board.txt"` ]]; then
+if [[ "$BOARD" == "odroidc4" ]]; then
 	MMC="/dev/mmcblk1";
 	OFFSET="2248";
 fi
-if [[ `grep -w 'BOARD="odroidn2"' "/etc/opt/board.txt"` ]]; then
+if [[ "$BOARD" == "odroidn2" ]]; then
 	MMC="/dev/mmcblk0";
 	OFFSET="2248";
 fi
-if [[ `grep -w 'BOARD="odroidn2plus"' "/etc/opt/board.txt"` ]]; then
+if [[ "$BOARD" == "odroidn2plus" ]]; then
 	MMC="/dev/mmcblk0";
 	OFFSET="2248";
 fi
-if [[ `grep -w 'BOARD="radxazero"' "/etc/opt/board.txt"` ]]; then
+if [[ "$BOARD" == "radxazero" ]]; then
 	MMC="/dev/mmcblk1";
 	OFFSET="2248";
 fi
 # rockchip
-if [[ `grep -w 'BOARD="nanopc"' "/etc/opt/board.txt"` ]]; then
+if [[ "$BOARD" == "nanopc" ]]; then
 	MMC="/dev/mmcblk2";
 	OFFSET="32767";
 fi
-if [[ `grep -w 'BOARD="renegade"' "/etc/opt/board.txt"` ]]; then
+if [[ "$BOARD" == "renegade" ]]; then
 	MMC="/dev/mmcblk1";
 	OFFSET="32767";
 fi
@@ -123,7 +123,7 @@ sleep 1s
 resize2fs ${MMC}p1
 }
 
-### RSYNC
+# rsync
 transfer(){
 cd /
 rsync -apvx --progress --stats --human-readable . /mnt > /dev/null 
@@ -145,7 +145,7 @@ done
 destroy_scroll_area
 }
 
-### FETCH UUID
+# uuid / partuuid
 fetch_uuid(){
 echo 'ROOT_UUID="' > root1
 blkid -o export -- ${MMC}p1 | sed -ne 's/^UUID=//p' > root2
@@ -160,7 +160,7 @@ paste -d '\0' root1 root2 root3  > /etc/opt/root-pid.txt
 rm -f root1 root2 root3
 }
 
-### FSTAB
+# fstab
 create_fstab(){
 rm -f /mnt/etc/fstab
 tee /mnt/etc/fstab <<EOF
@@ -169,9 +169,8 @@ tmpfs		/tmp	tmpfs	defaults,nosuid 0 0
 EOF
 }
 
-### EXTLINUX
+# extlinux
 create_extlinux(){
-source /etc/opt/board.txt > /dev/null 2>&1
 FDT="../${FAMILY}/${DTB}.dtb"
 FDTDIR="../${FAMILY}/"
 CMDLINE="append earlyprintk ${CONSOLE} rw root=PARTUUID=${ROOT_PARTUUID} rootwait rootfstype=ext4 fsck.repair=yes ${EXTRA} loglevel=1 init=/sbin/init"
@@ -186,51 +185,53 @@ label default
 	#fdtoverlays
 	${CMDLINE}
 EOF
-if [[ `grep -w 'BOARD="radxazero"' "/etc/opt/board.txt"` ]]; then
+if [[ "$BOARD" == "radxazero" ]]; then
 	sed -i 's/#fdtoverlays/fdtoverlays ..\/amlogic\/overlays\/meson-g12a-opp-2ghz.dtbo/g' /mnt/boot/extlinux/extlinux.conf;
+fi
+if [[ "$BOARD" == "nanopc" ]]; then
+	sed -i 's/#fdtoverlays/fdtoverlays ..\/rockchip\/overlays\/rockchip-rk3399-opp-2ghz.dtbo/g' p1/boot/extlinux/extlinux.conf;
 fi
 }
 
-
-### WRITE UBOOT
-# allwinner
-allwinner_flash_uboot(){
+# flash u-boot
+allwinner_flash_uboot(){ # allwinner
 dd if=/usr/lib/u-boot/u-boot-sunxi-with-spl.bin of=${MMC} conv=fsync bs=1024 seek=8
 sync
 }
 
-# amlogic
-amlogic_flash_uboot(){
+amlogic_flash_uboot(){ # amlogic
 dd if=/usr/lib/u-boot/u-boot.bin of=${MMC} bs=512 seek=1
 sync
 }
 
-# rockchip
-rockchip_flash_uboot(){
+rockchip_flash_uboot(){ # rockchip
 dd if=/usr/lib/u-boot/idbloader.bin of=${MMC} seek=64
 dd if=/usr/lib/u-boot/u-boot.itb of=${MMC} seek=16384
 sync
 }
 
-### THE MAGIC
-run_as_root
+# run
+if [ "$USER" != "root" ]; then
+        echo "Please run this as root or with sudo privileges.";
+        exit 1;
+fi
 echo ""
 confirm
 check_progressbar
 
-if [[ `grep -w 'BOARD="lepotato"' "/etc/opt/board.txt"` ]]; then
+if [[ "$BOARD" == "lepotato" ]]; then
 	echo ""
 	echo "Binding eMMC ...";
 	libre_bind_emmc;
 	echo "Done.";
 fi
-if [[ `grep -w 'FAMILY_EXT="odroid"' "/etc/opt/board.txt"` ]]; then
+if [[ "$FAMILY_EXT" == "odroid" ]]; then
 	echo ""
 	echo "Binding eMMC ...";
 	odroid_bind_emmc;
 	echo "Done.";
 fi
-if [[ `grep -w 'BOARD="renegade"' "/etc/opt/board.txt"` ]]; then
+if [[ "$BOARD" == "renegade" ]]; then
 	echo ""
 	echo "Binding eMMC ...";
 	renegade_bind_emmc;
@@ -251,13 +252,13 @@ clear -x
 
 echo ""
 echo "Writing u-boot ..."
-if [[ `grep -w 'FAMILY="allwinner"' "/etc/opt/board.txt"` ]]; then
+if [[ "$FAMILY" == "allwinner" ]]; then
 	allwinner_flash_uboot;
 fi
-if [[ `grep -w 'FAMILY="amlogic"' "/etc/opt/board.txt"` ]]; then
+if [[ "$FAMILY" == "amlogic" ]]; then
 	amlogic_flash_uboot;
 fi
-if [[ `grep -w 'FAMILY="rockchip"' "/etc/opt/board.txt"` ]]; then
+if [[ "$FAMILY" == "rockchip" ]]; then
 	rockchip_flash_uboot;
 fi
 echo "Done."
