Amlogic T7: Add second toolchain mirror
Signed-off-by: Patrick Yavitz <pyavitz@gmail.com>

diff --git a/lib/function/amlogic-t7 b/lib/function/amlogic-t7
--- a/lib/function/amlogic-t7
+++ b/lib/function/amlogic-t7
@@ -1,50 +1,67 @@
 #!/bin/bash
 
 DOWNLOAD="aria2c -c --download-result=hide --console-log-level=error --disable-ipv6=true --summary-interval=0 --show-files=false"
+# Mirrors
+AM_URL="https://mirrors.dotsrc.org/armbian-dl/_toolchain"
+GH_URL="https://github.com/pyavitz/debian-image-builder/releases/tag/toolchain"
+# Khadas VIM4 Compiler Toolchain
+if [[ "$HOST_ARCH" == "x86_64"  ]]; then TC_ARCH="linux-x64"; fi
+if [[ "$HOST_ARCH" == "aarch64"  ]]; then TC_ARCH="linux-${ARCH}"; fi
+ARM64_COMPILER="gcc-linaro-7.3.1-2018.05-${HOST_ARCH}_aarch64-elf"
+RISCV_COMPILER="xpack-riscv-none-embed-gcc-8.3.0-1.2"
+
+khadasvim4_toolchain_mirror (){
+if [[ `wget -S --spider ${AM_URL}/${ARM64_COMPILER}.tar.xz 2>&1 | grep 'HTTP/1.1 200 OK'` ]] && \
+	[[ `wget -S --spider ${AM_URL}/${RISCV_COMPILER}-${TC_ARCH}.tar.gz 2>&1 | grep 'HTTP/1.1 200 OK'` ]]; then TC_URL="${AM_URL}"
+elif [[ `wget -S --spider ${GH_URL}/${ARM64_COMPILER}.tar.xz 2>&1 | grep 'HTTP/1.1 200 OK'` ]] && \
+	[[ `wget -S --spider ${GH_URL}/${RISCV_COMPILER}-${TC_ARCH}.tar.gz 2>&1 | grep 'HTTP/1.1 200 OK'` ]]; then TC_URL="${GH_URL}"
+else
+	echo -e "${BOARD} toolchain mirror function failed to find tarball(s)."
+	echo -e "Check that you are connected to the webs and try again."
+	exit 1
+fi
+}
+
+# TOOLCHAIN
+khadasvim4_uboot_toolchain (){
+if [[ ! -d "${ARM64_COMPILER}" ]]; then
+	${BOARD}_toolchain_mirror
+	echo -en "${WHT}${ARM64_COMPILER}${FIN} "
+	sleep .25
+	echo -en "${PNK}[${FIN}${WHT}downloading${FIN}${PNK}]${FIN} "
+	sleep .50
+	${DOWNLOAD} ${TC_URL}/${ARM64_COMPILER}.tar.xz
+	if [[ -f "${ARM64_COMPILER}.tar.xz" ]]; then
+		echo -en " ${PNK}[${FIN}${WHT}extracting${FIN}${PNK}]${FIN} "
+		tar xf ${ARM64_COMPILER}.tar.xz
+		if [[ ! -d "${ARM64_COMPILER}" ]]; then report_error; else echo_bdone; fi
+	else
+		echo -e "${PNK}[${FIN}${RED}failed${FIN}${PNK}]${FIN}"
+		exit 1
+	fi
+fi
+if [[ ! -d "${RISCV_COMPILER}" ]]; then
+	${BOARD}_toolchain_mirror
+	echo -en "${WHT}${RISCV_COMPILER}${FIN} "
+	sleep .25
+	echo -en "${PNK}[${FIN}${WHT}downloading${FIN}${PNK}]${FIN} "
+	sleep .50
+	${DOWNLOAD} ${TC_URL}/${RISCV_COMPILER}-${TC_ARCH}.tar.gz
+	if [[ -f "${RISCV_COMPILER}-${TC_ARCH}.tar.gz" ]]; then
+		echo -en " ${PNK}[${FIN}${WHT}extracting${FIN}${PNK}]${FIN} "
+		tar xf ${RISCV_COMPILER}-${TC_ARCH}.tar.gz
+		if [[ ! -d "${RISCV_COMPILER}" ]]; then report_error; else echo_bdone; fi
+	else
+		echo -e "${PNK}[${FIN}${RED}failed${FIN}${PNK}]${FIN}"
+		exit 1
+	fi
+fi
+}
 
 # U-BOOT
 amlogic_uboot_download (){
 if [[ "$SERIES" == "amlogic-t7" ]]; then
-	if [[ "$HOST_ARCH" == "x86_64"  ]]; then TC_ARCH="linux-x64"; else TC_ARCH="linux-${ARCH}"; fi
-	# Download toolchain from Armbian Mirror
-	TC_URL="https://mirrors.dotsrc.org/armbian-dl/_toolchain"
-	# Khadas VIM4 Compiler Toolchain
-	ARM64_COMPILER="gcc-linaro-7.3.1-2018.05-${HOST_ARCH}_aarch64-elf"
-	RISCV_COMPILER="xpack-riscv-none-embed-gcc-8.3.0-1.2"
-	if [[ ! -d "${ARM64_COMPILER}" ]]; then
-		if [[ `wget -S --spider ${TC_URL}/${ARM64_COMPILER}.tar.xz 2>&1 | grep 'HTTP/1.1 200 OK'` ]]; then
-			echo -en "${WHT}${ARM64_COMPILER}${FIN} "
-			sleep .25
-			echo -en "${PNK}[${FIN}${WHT}downloading${FIN}${PNK}]${FIN} "
-			sleep .50
-			${DOWNLOAD} ${TC_URL}/${ARM64_COMPILER}.tar.xz
-			if [[ -f "${ARM64_COMPILER}.tar.xz" ]]; then
-				echo -en " ${PNK}[${FIN}${WHT}extracting${FIN}${PNK}]${FIN} "
-				tar xf ${ARM64_COMPILER}.tar.xz
-				if [[ ! -d "${ARM64_COMPILER}" ]]; then report_error; else echo_bdone; fi
-			else
-				echo -e "${PNK}[${FIN}${RED}failed${FIN}${PNK}]${FIN}"
-				exit 1
-			fi
-		fi
-	fi
-	if [[ ! -d "${RISCV_COMPILER}" ]]; then
-		if [[ `wget -S --spider ${TC_URL}/${RISCV_COMPILER}-${TC_ARCH}.tar.gz 2>&1 | grep 'HTTP/1.1 200 OK'` ]]; then
-			echo -en "${WHT}${RISCV_COMPILER}${FIN} "
-			sleep .25
-			echo -en "${PNK}[${FIN}${WHT}downloading${FIN}${PNK}]${FIN} "
-			sleep .50
-			${DOWNLOAD} ${TC_URL}/${RISCV_COMPILER}-${TC_ARCH}.tar.gz
-			if [[ -f "${RISCV_COMPILER}-${TC_ARCH}.tar.gz" ]]; then
-				echo -en " ${PNK}[${FIN}${WHT}extracting${FIN}${PNK}]${FIN} "
-				tar xf ${RISCV_COMPILER}-${TC_ARCH}.tar.gz
-				if [[ ! -d "${RISCV_COMPILER}" ]]; then report_error; else echo_bdone; fi
-			else
-				echo -e "${PNK}[${FIN}${RED}failed${FIN}${PNK}]${FIN}"
-				exit 1
-			fi
-		fi
-	fi
+	${BOARD}_uboot_toolchain
 	GIT_UBOOT_HASH=`git ls-remote --heads ${GIT_UBOOT_URL} | grep -w "refs/heads/${GIT_UBOOT_TAG}" | sed -n '1p' | sed "s/refs\/heads\/${GIT_UBOOT_TAG}//g" | sed s/'\s'//g`
 	GIT_UBOOT_COMMIT="4a16015168d00d08487781fc914e048944554c6e"
 	if [[ ! "$GIT_UBOOT_COMMIT" == "$GIT_UBOOT_HASH" ]]; then rm -fdr ${BOARD}-u-boot-${GIT_UBOOT_TAG}; fi
