ATF: If download fails alert user.
Signed-off-by: Patrick Yavitz <pyavitz@gmail.com>

diff --git a/lib/function/atf b/lib/function/atf
--- a/lib/function/atf
+++ b/lib/function/atf
@@ -48,6 +48,11 @@ if [[ `wget -S --spider https://github.com/ARM-software/arm-trusted-firmware/blo
 			exit 1
 		fi
 	fi
+else
+	echo -en "arm-trusted-firmware-${ATF_TAG}"
+	echo -e ", download failed."
+	echo -e "Check internet connection."
+	exit 1
 fi
 }
 
