check for `crust` and `u-boot` defconfig before compilation
Signed-off-by: Patrick Yavitz <pyavitz@xxxxx.com>

diff --git a/lib/function/crust b/lib/function/crust
--- a/lib/function/crust
+++ b/lib/function/crust
@@ -34,23 +34,24 @@ if [[ "$SERIES" =~ ^(sun50i-a64|sun50i-h5|sun50i-h6)$ ]]; then
 			echo_bdone
 		else
 			echo -e "${PNK}[${FIN}${RED}failed${FIN}${PNK}]${FIN}"
-			exit 0
+			exit 1
 		fi
 	fi
 	echo ""
 	crust_defconfig
-	if [ $CROSSCOMPILE -eq 1 ]; then
-		echo -e "${GRN}  CC${FIN}"
+	if [[ -f "configs/${CRUST_DEFCONFIG}" ]]; then
+		if [ $CROSSCOMPILE -eq 1 ]; then echo -e "${GRN}  CC${FIN}"; else echo -e "${GRN}  NC${FIN}"; fi
 		make -j${CORES} ARCH=${ARCH} CROSS_COMPILE=or1k-elf- ${CRUST_DEFCONFIG}
 		make -j${CORES} ARCH=${ARCH} CROSS_COMPILE=or1k-elf-
 	else
-		echo -e "${GRN}  NC${FIN}"
-		make -j${CORES} ARCH=${ARCH} CROSS_COMPILE=or1k-elf- ${CRUST_DEFCONFIG}
-		make -j${CORES} ARCH=${ARCH} CROSS_COMPILE=or1k-elf-
+		echo ""
+		echo -e "${CRUST_DEFCONFIG} was not found."
+		echo -e "Check that the name is correct in the lib/boards/${BOARD} file."
+		echo -e ""
+		read -p "Press enter to continue."
+		exit 1
 	fi
-	if [[ "$BOARD" == "orangepi3lts" ]]; then
-		rm -f configs/${UBOOT_DEFCONFIG}
-	fi
+	if [[ "$BOARD" == "orangepi3lts" ]]; then rm -f configs/${UBOOT_DEFCONFIG}; fi
 	cd ..
 	echo ""
 fi
@@ -59,5 +60,5 @@ fi
 report_crust_error (){
 echo "Missing crust scp.bin blob. Please report build errors."
 echo ""
-exit 0
+exit 1
 }
diff --git a/lib/function/uboot b/lib/function/uboot
--- a/lib/function/uboot
+++ b/lib/function/uboot
@@ -12,7 +12,7 @@ rm -fdr {imx-mkimage,u-boot}
 report_error (){
 echo "Something went wrong? Please report."
 echo ""
-exit 0
+exit 1
 }
 
 download_uboot (){
@@ -35,7 +35,7 @@ if [[ `wget -S --spider https://source.denx.de/u-boot/u-boot/-/archive/${UBOOT_V
 else
 	echo ""
 	echo -e "${WHT}Version selected is not available.${FIN}"
-	exit 0
+	exit 1
 fi
 }
 
@@ -56,12 +56,21 @@ if [[ -f "u-boot-${UBOOT_VERSION}.tar.gz" ]]; then
 	mv -f u-boot-${UBOOT_VERSION} u-boot
 else
 	echo -e "Missing u-boot-${UBOOT_VERSION} tarball."
-	exit 0
+	exit 1
 fi
 }
 
 defconfig (){
-ubuild "${UBOOT_DEFCONFIG}"
+if [[ -f "configs/${UBOOT_DEFCONFIG}" ]]; then
+	ubuild "${UBOOT_DEFCONFIG}"
+else
+	echo ""
+	echo -e "${UBOOT_DEFCONFIG} was not found."
+	echo -e "Check that the name is correct in the lib/boards/${BOARD} file."
+	echo -e ""
+	read -p "Press enter to continue."
+	exit 1
+fi
 }
 
 menuconfig (){
