Staging: Move *.img to output dir.
Signed-off-by: Patrick Yavitz <pyavitz@gmail.com>

diff --git a/lib/function/staging b/lib/function/staging
--- a/lib/function/staging
+++ b/lib/function/staging
@@ -514,21 +514,22 @@ fi
 
 # rename and check for compression
 finish_image (){
+mkdir -p ${OUTPUT}/image
 IMAGE_TIME="$(date +%T | sed 's/://g' | sed 's/..$//')"
 if [[ "$MINIMAL_ROOTFS" == "false" ]]; then
 	IMAGE_FIN_NAME="${DEVICE_SOC}-${DISTRO}-${DISTRO_VERSION}-${INSTALLED_KERNEL}-${ARCH_EXT}-${FSTYPE}-${IMAGE_DATE}-${IMAGE_TIME}.img"
 else
 	IMAGE_FIN_NAME="${DEVICE_SOC}-${DISTRO}-${DISTRO_VERSION}-minimal-${INSTALLED_KERNEL}-${ARCH_EXT}-${FSTYPE}-${IMAGE_DATE}-${IMAGE_TIME}.img"
 fi
-if [[ -f "${IMAGE_FILE_NAME}" ]]; then mv -f ${IMAGE_FILE_NAME} ${IMAGE_FIN_NAME}; else echo -e "Build error: ${IMAGE_FILE_NAME}"; exit 1; fi
+if [[ -f "${IMAGE_FILE_NAME}" ]]; then mv -f ${IMAGE_FILE_NAME} ${OUTPUT}/image/${IMAGE_FIN_NAME}; else echo -e "Build error: ${IMAGE_FILE_NAME}"; exit 1; fi
 if [ $COMPRESS_IMG -eq 1 ]; then
 	echo ""
 	echo -e "Compressing image ..."
-	if [[ "$IMG_COMPRESSION" == "xz" ]]; then xz -zev --threads=${CORES} ${IMAGE_FIN_NAME}; fi
-	if [[ "$IMG_COMPRESSION" == "zst" ]]; then zstd -z --ultra --fast=10 -19 -T${CORES} --rm ${IMAGE_FIN_NAME}; fi
-	if [[ -f "${IMAGE_FIN_NAME}.${IMG_COMPRESSION}" ]]; then
-		sha256sum ${IMAGE_FIN_NAME}.${IMG_COMPRESSION} > ${IMAGE_FIN_NAME}.${IMG_COMPRESSION}.sha256
-		sha256sum --check ${IMAGE_FIN_NAME}.${IMG_COMPRESSION}.sha256
+	if [[ "$IMG_COMPRESSION" == "xz" ]]; then xz -zev --threads=${CORES} ${OUTPUT}/image/${IMAGE_FIN_NAME}; fi
+	if [[ "$IMG_COMPRESSION" == "zst" ]]; then zstd -z --ultra --fast=10 -19 -T${CORES} --rm ${OUTPUT}/image/${IMAGE_FIN_NAME}; fi
+	if [[ -f "${OUTPUT}/image/${IMAGE_FIN_NAME}.${IMG_COMPRESSION}" ]]; then
+		sha256sum ${OUTPUT}/image/${IMAGE_FIN_NAME}.${IMG_COMPRESSION} > ${OUTPUT}/image/${IMAGE_FIN_NAME}.${IMG_COMPRESSION}.sha256
+		sha256sum --check ${OUTPUT}/image/${IMAGE_FIN_NAME}.${IMG_COMPRESSION}.sha256
 	fi
 fi
 }
