Packaging: Update legacy overlay support
Signed-off-by: Patrick Yavitz <pyavitz@gmail.com>

diff --git a/packaging/legacy/builddeb b/packaging/legacy/builddeb
--- a/packaging/legacy/builddeb
+++ b/packaging/legacy/builddeb
@@ -43,6 +43,12 @@ else
 	echo "Missing scripts/package/pkgvars!"
 	exit 1
 fi
+if [ -f "scripts/package/overlays" ]; then
+	. scripts/package/overlays
+else
+	echo "Missing scripts/package/overlays!"
+	exit 1
+fi
 if [ ! -f "dtclist.txt" ]; then echo "Missing dtclist.txt!"; exit 1; fi
 if [ ! -f "initrd" ]; then echo "Missing initrd!"; exit 1; fi
 if [ ! -f "headers-byteshift.patch" ]; then echo "Missing headers-byteshift.patch!"; exit 1; fi
@@ -155,47 +161,19 @@ fi
 
 # Update dtb list
 for dtclist in `cat dtclist.txt`; do ls $tmpdir/$linux_path/$dtclist 2>/dev/null | tee -a dtclist.new > /dev/null 2>&1; done
-#grep ".dtb" "dtclist.txt" | echo "  CHKLIST `wc -l`"
 rm -f "dtclist.txt"; mv -f "dtclist.new" "dtclist.txt"
 
 # Installing dtb files
 if [ -d $tmpdir/$linux_path ]; then
 	mkdir -p "$tmpdir/$boot_path"
-	#grep ".dtb" "dtclist.txt" | echo "  CHKINST `wc -l`"
-	#grep ".dtb" "dtclist.txt" | sed 's/^/  DTBINST /' | sed "s/.\/debian\/tmp\/usr\/lib\/$linux_name/boot/g" | sort -n -t _ -k 2
+	# Installing dtb files
 	for dtclist in `cat dtclist.txt`; do cp -r "$dtclist" 2>/dev/null "$tmpdir/$boot_path"; done
 	rm -f dtclist.txt
 	# install overlays
-	if ls arch/$karch/boot/dts/overlays/*.dtbo > /dev/null 2>&1; then
-		mkdir -p "$tmpdir/$linux_path/overlays"
-		cp -r arch/$karch/boot/dts/overlays/*.dtbo "$tmpdir/$linux_path/overlays"
-	fi
-	# install mainline overlays
-	if ls arch/$karch/boot/dts/$platform/*.dtbo > /dev/null 2>&1; then
-		mkdir -p "$tmpdir/$linux_path/overlays"
-		cp -r arch/$karch/boot/dts/$platform/*.dtbo "$tmpdir/$linux_path/overlays"
-	fi
-	# install git overlays
-	if ls $tmpdir/$linux_path/*.dtbo > /dev/null 2>&1; then
-		mkdir -p "$tmpdir/$linux_path/overlays"
-		mv -f $tmpdir/$linux_path/*.dtbo "$tmpdir/$linux_path/overlays"
-	fi
-	if [ -d "$tmpdir/$linux_path/overlays" ]; then
-		mkdir -p "$tmpdir/$boot_path/overlays"
-		cp -r "$tmpdir/$linux_path/overlays" "$tmpdir/$boot_path"
-	else
-		# check for vendor overlays
-		if [ -d "$tmpdir/$linux_path/overlay" ]; then
-			mkdir -p "$tmpdir/$boot_path/overlays"
-			mv -f "$tmpdir/$linux_path/overlay" "$tmpdir/$linux_path/overlays"
-			cp -r "$tmpdir/$linux_path/overlays" "$tmpdir/$boot_path"
-		fi
-	fi
-	# fixup broadcom overlays
 	if [ "$platform" = "broadcom" ] && [ -d "$tmpdir/usr/lib/$linux_name/overlays" ]; then
-		rm -fdr "$tmpdir/$linux_path/overlays"
-		rm -fdr "$tmpdir/$boot_path/overlays"
-		mv -f "$tmpdir/usr/lib/$linux_name/overlays" "$tmpdir/$boot_path/overlays"
+		cp -fr "$tmpdir/usr/lib/$linux_name/overlays" "$tmpdir/$boot_path/overlays"
+	else
+		linux_packaging_overlays
 	fi
 fi
 
