Dialog Menu: `maintenance`
Signed-off-by: Patrick Yavitz <pyavitz@gmail.com>

diff --git a/lib/dialog/general b/lib/dialog/general
--- a/lib/dialog/general
+++ b/lib/dialog/general
@@ -18,86 +18,84 @@ while true; do
 	--cancel-label "Exit" \
 	--menu "Select:" $HEIGHT $WIDTH 4 \
 	"1" "Make All ..." \
-	"2" "Make Das U-Boot" \
+	"2" "Make U-Boot" \
 	"3" "Make Linux Kernel" \
 	"4" "Make Root Filesystem" \
-	"5" "Make Flashable Image" \
+	"5" "Make Image" \
 	2>&1 1>&3)
 	exit_status=$?
 	exec 3>&-;
-case $exit_status in
-	$DIALOG_CANCEL)
-		clear
-		echo "Program terminated."
-		exit 0
-		;;
-	$DIALOG_ESC)
-		clear
-		echo "Program aborted." >&2
-		exit 1
-		;;
-esac
-case $selection in
-	0 )
-		clear
-		echo "Program terminated."
-		;;
-	1 )
-		if [ $LOGGING -eq 1 ]; then
-			echo LOGNAME=$1 > logger.txt
-			echo 'LOGFILE="$LOGNAME-all"' >> logger.txt
-			./scripts/loggit make "all" "board=$1"
-		else
-			make "all" "board=$1"
-		fi
-		dialog --prgbox "Results:" "ls $IMG_EXP ${DISTRO}-${DISTRO_VERSION}-${ROOTFS_ARCH}* $MAKE_OUTPUT/" 30 75
-		exit 0
-		;;
-	2 )
-		if [[ "$FAMILY" == "generic" ]]; then
-			:;
-		elif [ $LOGGING -eq 1 ]; then
-			echo LOGNAME=$1 > logger.txt
-			echo 'LOGFILE="$LOGNAME-u-boot"' >> logger.txt
-			./scripts/loggit make "uboot" "board=$1"
-		else
-			make "uboot" "board=$1"
-		fi
-		if [[ "$FAMILY" == "generic" ]]; then
-			:;
-		else
-			dialog --prgbox "Results:" "ls $MAKE_OUTPUT/*.bin; ls $MAKE_OUTPUT/u-boot-*.deb" 30 75;
-		fi
-		;;
-	3 )
-		if [ $LOGGING -eq 1 ]; then
-			echo LOGNAME=$1 > logger.txt
-			echo 'LOGFILE="$LOGNAME-linux"' >> logger.txt
-			./scripts/loggit make "kernel" "board=$1"
-		else
-			make "kernel" "board=$1"
-		fi
-		dialog --prgbox "Results:" "ls $MAKE_OUTPUT/linux-*.deb" 30 75
-		;;
-	4 )
-		if [ $LOGGING -eq 1 ]; then
-			echo LOGNAME=$1 > logger.txt
-			echo 'LOGFILE="$LOGNAME-rootfs"' >> logger.txt
-			./scripts/loggit make "rootfs" "board=$1"
-		else
-			make "rootfs" "board=$1"
-		fi
-		dialog --prgbox "Results:" "ls ${DISTRO}-${DISTRO_VERSION}-${ROOTFS_ARCH}*" 30 75
-		;;
-	5 )
-		if [ $LOGGING -eq 1 ]; then
-			echo LOGNAME=$1 > logger.txt
-			echo 'LOGFILE="$LOGNAME-image"' >> logger.txt
-			./scripts/loggit make "image" "board=$1"
-		else
-			make "image" "board=$1"
-		fi
-		dialog --prgbox "Results:" "ls $IMG_EXP" 30 75
-		;;
-esac
+	case $exit_status in
+		$DIALOG_CANCEL)
+			clear
+			echo "Program terminated."
+			exit 0
+			;;
+		$DIALOG_ESC)
+			clear
+			echo "Program aborted." >&2
+			exit 1
+			;;
+	esac
+	case $selection in
+		0 )
+			clear
+			echo "Program terminated."
+			;;
+		1 )
+			if [ $LOGGING -eq 1 ]; then
+				echo LOGNAME=$1 > logger.txt
+				echo 'LOGFILE="$LOGNAME-all"' >> logger.txt
+				./scripts/loggit make "all" "board=$1"
+			else
+				make "all" "board=$1"
+			fi
+			dialog --backtitle "$BTITLE" --prgbox "Results:" "ls $IMG_EXP ${DISTRO}-${DISTRO_VERSION}-${ROOTFS_ARCH}* $MAKE_OUTPUT/" 30 75
+			exit 0
+			;;
+		2 )
+			if [[ "$FAMILY" == "generic" ]]; then
+				:;
+			elif [ $LOGGING -eq 1 ]; then
+				echo LOGNAME=$1 > logger.txt
+				echo 'LOGFILE="$LOGNAME-u-boot"' >> logger.txt
+				./scripts/loggit make "uboot" "board=$1"
+			else
+				make "uboot" "board=$1"
+			fi
+			if [[ ! "$FAMILY" == "generic" ]]; then
+				dialog --backtitle "$BTITLE" --prgbox "Results:" "ls $MAKE_OUTPUT/*.bin; ls $MAKE_OUTPUT/u-boot-*.deb" 30 75
+			fi
+			;;
+		3 )
+			if [ $LOGGING -eq 1 ]; then
+				echo LOGNAME=$1 > logger.txt
+				echo 'LOGFILE="$LOGNAME-linux"' >> logger.txt
+				./scripts/loggit make "kernel" "board=$1"
+			else
+				make "kernel" "board=$1"
+			fi
+			dialog --backtitle "$BTITLE" --prgbox "Results:" "ls $MAKE_OUTPUT/linux-*.deb" 30 75
+			;;
+		4 )
+			if [ $LOGGING -eq 1 ]; then
+				echo LOGNAME=$1 > logger.txt
+				echo 'LOGFILE="$LOGNAME-rootfs"' >> logger.txt
+				./scripts/loggit make "rootfs" "board=$1"
+			else
+				make "rootfs" "board=$1"
+			fi
+			dialog --backtitle "$BTITLE" --prgbox "Results:" "ls ${DISTRO}-${DISTRO_VERSION}-${ROOTFS_ARCH}*" 30 75
+			;;
+		5 )
+			if [ $LOGGING -eq 1 ]; then
+				echo LOGNAME=$1 > logger.txt
+				echo 'LOGFILE="$LOGNAME-image"' >> logger.txt
+				./scripts/loggit make "image" "board=$1"
+			else
+				make "image" "board=$1"
+			fi
+			dialog --backtitle "$BTITLE" --prgbox "Results:" "ls $IMG_EXP" 30 75
+			;;
+	esac
 done
