Menu Interface: `maintenance`

diff --git a/lib/dialog/general b/lib/dialog/general
--- a/lib/dialog/general
+++ b/lib/dialog/general
@@ -8,58 +8,58 @@ HEIGHT=0
 WIDTH=0
 
 while true; do
-  exec 3>&1
-  selection=$(dialog \
-    --backtitle "Debian Image Builder" \
-    --title "$1" \
-    --clear \
-    --cancel-label "Exit" \
-    --menu "Select:" $HEIGHT $WIDTH 5 \
-    "1" "Make All" \
-    "2" "Make U-Boot" \
-    "3" "Make Kernel" \
-    "4" "Make ROOTFS" \
-    "5" "Make Image" \
-    2>&1 1>&3)
-  exit_status=$?
-  exec 3>&-;
-  case $exit_status in
-    $DIALOG_CANCEL)
-      clear
-      echo "Program terminated."
-      exit
-      ;;
-    $DIALOG_ESC)
-      clear
-      echo "Program aborted." >&2
-      exit 1
-      ;;
-  esac
-  case $selection in
-    0 )
-      clear
-      echo "Program terminated."
-      ;;
-    1 )
-      make "all" "board=$1"
-      dialog --prgbox "Results:" "ls $IMG_EXP *$ARCH_EXT* $MAKE_OUTPUT/" 30 75
-      exit 0
-      ;;
-    2 )
-      make uboot "board=$1"
-      dialog --prgbox "Results:" "ls $MAKE_OUTPUT/*.bin" 30 75
-      ;;
-    3 )
-      make kernel "board=$1"
-      dialog --prgbox "Results:" "ls $MAKE_OUTPUT/*.deb" 30 75
-      ;;
-    4 )
-      make rootfs "board=$1"
-      dialog --prgbox "Results:" "ls *$ARCH_EXT*" 30 75
-      ;;
-    5 )
-      make image "board=$1"
-      dialog --prgbox "Results:" "ls $IMG_EXP" 30 75
-      ;;
-  esac
+	exec 3>&1
+	selection=$(dialog \
+	--backtitle "Debian Image Builder" \
+	--title "$1" \
+	--clear \
+	--cancel-label "Exit" \
+	--menu "Select:" $HEIGHT $WIDTH 5 \
+	"1" "Make All" \
+	"2" "Make U-Boot" \
+	"3" "Make Kernel" \
+	"4" "Make ROOTFS" \
+	"5" "Make Image" \
+	2>&1 1>&3)
+	exit_status=$?
+	exec 3>&-;
+case $exit_status in
+	$DIALOG_CANCEL)
+		clear
+		echo "Program terminated."
+		exit
+	;;
+	$DIALOG_ESC)
+		clear
+		echo "Program aborted." >&2
+		exit 1
+	;;
+esac
+case $selection in
+	0 )
+		clear
+		echo "Program terminated."
+	;;
+	1 )
+		make "all" "board=$1"
+		dialog --prgbox "Results:" "ls $IMG_EXP *$ARCH_EXT* $MAKE_OUTPUT/" 30 75
+		exit 0
+	;;
+	2 )
+		make "uboot" "board=$1"
+		dialog --prgbox "Results:" "ls $MAKE_OUTPUT/*.bin" 30 75
+	;;
+	3 )
+		make "kernel" "board=$1"
+		dialog --prgbox "Results:" "ls $MAKE_OUTPUT/*.deb" 30 75
+	;;
+	4 )
+		make "rootfs" "board=$1"
+		dialog --prgbox "Results:" "ls *$ARCH_EXT*" 30 75
+	;;
+	5 )
+		make "image" "board=$1"
+		dialog --prgbox "Results:" "ls $IMG_EXP" 30 75
+	;;
+esac
 done
