`Debian Image Builder`
armhf crossbuild depends

diff --git a/lib/dialog/menu b/lib/dialog/menu
--- a/lib/dialog/menu
+++ b/lib/dialog/menu
@@ -30,98 +30,117 @@ fi
 validation
 
 while true; do
-  exec 3>&1
-  selection=$(dialog \
-    --backtitle "Debian Image Builder" \
-    --title "Boards" \
-    --clear \
-    --cancel-label "Exit" \
-    --menu "Select:" $HEIGHT $WIDTH 11 \
-    "1" "Le Potato" \
-    "2" "NanoPC-T4" \
-    "3" "NanoPi NEO Plus2" \
-    "4" "Odroid C4" \
-    "5" "Odroid N2" \
-    "6" "Odroid N2+" \
-    "7" "Pine64" \
-    "8" "Radxa Zero" \
-    "9" "Raspberry Pi 4B" \
-    "10" "Renegade" \
-    "11" "Rock64" \
-    "12" "RockPro64" \
-    "13" "Tritium" \
-    2>&1 1>&3)
-  exit_status=$?
-  exec 3>&-;
-  case $exit_status in
-    $DIALOG_CANCEL)
-      clear
-      echo -e "${RED}Program terminated${FIN}."
-      exit
-      ;;
-    $DIALOG_ESC)
-      clear
-      echo -e "${RED}Program aborted${FIN}." >&2
-      exit 1
-      ;;
-  esac
-  case $selection in
-    0 )
-      clear
-      echo -e "${RED}Program terminated${FIN}."
-      ;;
-    1 )
-      chmod +x lib/dialog/lepotato
-      ./lib/dialog/lepotato
-      ;;
-    2 )
-      chmod +x lib/dialog/nanopct4
-      ./lib/dialog/nanopct4
-      ;;
-    3 )
-      chmod +x lib/dialog/npineoplus2
-      ./lib/dialog/npineoplus2
-      ;;
-    4 )
-      chmod +x lib/dialog/odroidc4
-      ./lib/dialog/odroidc4
-      ;;
-    5 )
-      chmod +x lib/dialog/odroidn2
-      ./lib/dialog/odroidn2
-      ;;
-    6 )
-      chmod +x lib/dialog/odroidn2+
-      ./lib/dialog/odroidn2+
-      ;;
-    7 )
-      chmod +x lib/dialog/pine64
-      ./lib/dialog/pine64
-      ;;
-    8 )
-      chmod +x lib/dialog/rzero
-      ./lib/dialog/rzero
-      ;;
-    9 )
-      chmod +x lib/dialog/raspi4
-      ./lib/dialog/raspi4
-      ;;
-    10 )
-      chmod +x lib/dialog/renegade
-      ./lib/dialog/renegade
-      ;;
-    11 )
-      chmod +x lib/dialog/rock64
-      ./lib/dialog/rock64
-      ;;
-    12 )
-      chmod +x lib/dialog/rockpro64
-      ./lib/dialog/rockpro64
-      ;;
-    13 )
-      chmod +x lib/dialog/tritium
-      ./lib/dialog/tritium
-      ;;
-
-  esac
+	exec 3>&1
+	selection=$(dialog \
+	--backtitle "Debian Image Builder" \
+	--title "Boards" \
+	--clear \
+	--cancel-label "Exit" \
+	--menu "Select:" $HEIGHT $WIDTH 15 \
+	"1" "Le Potato" \
+	"2" "NanoPC-T4" \
+	"3" "NanoPi NEO" \
+	"4" "NanoPi NEO Plus2" \
+	"5" "NanoPi M1" \
+	"6" "Odroid C4" \
+	"7" "Odroid N2" \
+	"8" "Odroid N2+" \
+	"9" "OrangePi One" \
+	"10" "OrangePi PC" \
+	"11" "Pine64" \
+	"12" "Radxa Zero" \
+	"13" "Raspberry Pi 4B" \
+	"14" "Renegade" \
+	"15" "Rock64" \
+	"16" "RockPro64" \
+	"17" "Tritium" \
+ 	2>&1 1>&3)
+ 	exit_status=$?
+ 	exec 3>&-;
+case $exit_status in
+	$DIALOG_CANCEL)
+		clear
+		echo -e "${RED}Program terminated${FIN}."
+		exit
+		;;
+	$DIALOG_ESC)
+		clear
+		echo -e "${RED}Program aborted${FIN}." >&2
+		exit 1
+		;;
+esac
+case $selection in
+	0 )
+		clear
+		echo -e "${RED}Program terminated${FIN}."
+		;;
+	1 )
+		chmod +x lib/dialog/lepotato
+	      ./lib/dialog/lepotato
+		;;
+	2 )
+		chmod +x lib/dialog/nanopct4
+		./lib/dialog/nanopct4
+		;;
+	3 )
+		chmod +x lib/dialog/npineo
+		./lib/dialog/npineo
+		;;
+	4 )
+		chmod +x lib/dialog/npineoplus2
+		./lib/dialog/npineoplus2
+		;;
+	5 )
+		chmod +x lib/dialog/npim1
+		./lib/dialog/npim1
+		;;
+	6 )
+		chmod +x lib/dialog/odroidc4
+		./lib/dialog/odroidc4
+		;;
+	7 )
+		chmod +x lib/dialog/odroidn2
+		./lib/dialog/odroidn2
+		;;
+	8 )
+		chmod +x lib/dialog/odroidn2+
+		./lib/dialog/odroidn2+
+		;;
+	9 )
+		chmod +x lib/dialog/opione
+		./lib/dialog/opione
+		;;
+	10 )
+		chmod +x lib/dialog/opipc
+		./lib/dialog/opipc
+		;;
+	11 )
+		chmod +x lib/dialog/pine64
+		./lib/dialog/pine64
+		;;
+	12 )
+		chmod +x lib/dialog/rzero
+		./lib/dialog/rzero
+		;;
+	13 )
+		chmod +x lib/dialog/raspi4
+		./lib/dialog/raspi4
+		;;
+	14 )
+		chmod +x lib/dialog/renegade
+		./lib/dialog/renegade
+		;;
+	15 )
+		chmod +x lib/dialog/rock64
+		./lib/dialog/rock64
+		;;
+	16 )
+		chmod +x lib/dialog/rockpro64
+		./lib/dialog/rockpro64
+		;;
+	17 )
+		chmod +x lib/dialog/tritium
+		./lib/dialog/tritium
+		;;
+	esac
 done
