092620
Added NanoPC-T4 to menu interface.
Rockchip: No longer requires the use of rkbin.
Rockchip: All boards now use arm trusted firmware and mainline uboot method.
dd if=idbloader.bin of=/dev/sdx seek=64 dd if=u-boot.itb of=/dev/sdx seek=16384
Removed individual source directories and replaced with one: sources

diff --git a/lib/menu b/lib/menu
--- a/lib/menu
+++ b/lib/menu
@@ -20,63 +20,64 @@ while true; do
     --title "Boards" \
     --clear \
     --cancel-label "Exit" \
-    --menu "Select:" $HEIGHT $WIDTH 9 \
+    --menu "Select:" $HEIGHT $WIDTH 10 \
     "1" "Le Potato" \
-    "2" "Odroid C4" \
-    "3" "Odroid N2" \
-    "4" "NanoPi NEO Plus2" \
-    "5" "Orange Pi R1" \
-    "6" "Pine64" \
-    "7" "Tritium" \
+    "2" "NanoPC-T4" \
+    "3" "NanoPi NEO Plus2" \
+    "4" "Odroid C4" \
+    "5" "Odroid N2" \
+    "6" "Orange Pi R1" \
+    "7" "Pine64" \
     "8" "Renegade" \
     "9" "Rock64" \
+    "10" "Tritium" \
     2>&1 1>&3)
   exit_status=$?
   exec 3>&-;
   case $exit_status in
     $DIALOG_CANCEL)
       clear
-      echo -e "${RED}Program terminated.${FIN}"
+      echo -e "${RED}Program terminated${FIN}."
       exit
       ;;
     $DIALOG_ESC)
       clear
-      echo -e "${RED}Program aborted.${FIN}" >&2
+      echo -e "${RED}Program aborted${FIN}." >&2
       exit 1
       ;;
   esac
   case $selection in
     0 )
       clear
-      echo -e "${RED}Program terminated.${FIN}"
+      echo -e "${RED}Program terminated${FIN}."
       ;;
     1 )
       chmod +x lib/lepotato
       ./lib/lepotato
       ;;
     2 )
-      chmod +x lib/odroidc4
-      ./lib/odroidc4
+      chmod +x lib/nanopct4
+      ./lib/nanopct4
       ;;
     3 )
-      chmod +x lib/odroidn2
-      ./lib/odroidn2
-      ;;
-    4 )
       chmod +x lib/npineoplus2
       ./lib/npineoplus2
       ;;
+    4 )
+      chmod +x lib/odroidc4
+      ./lib/odroidc4
+      ;;
     5 )
+      chmod +x lib/odroidn2
+      ./lib/odroidn2
+      ;;
+    6 )
       chmod +x lib/opir1
       ./lib/opir1
       ;;
-    6 )
+    7 )
       chmod +x lib/pine64
       ./lib/pine64
-      ;;
-    7 )
-      chmod +x lib/tritium
-      ./lib/tritium
       ;;
     8 )
       chmod +x lib/renegade
@@ -86,5 +87,10 @@ while true; do
       chmod +x lib/rock64
       ./lib/rock64
       ;;
+    10 )
+      chmod +x lib/tritium
+      ./lib/tritium
+      ;;
+
   esac
 done
