Move rootfs tarballs to output dir.
Signed-off-by: Patrick Yavitz <pyavitz@gmail.com>

diff --git a/scripts/rootfs b/scripts/rootfs
--- a/scripts/rootfs
+++ b/scripts/rootfs
@@ -39,7 +39,8 @@ if [[ "$MINIMAL_ROOTFS" == "false" ]]; then
 else
 	RELEASE_TARBALL=${DISTRO}-${DISTRO_VERSION}-minimal-${ROOTFS_ARCH}
 fi
-if [[ -f "${RELEASE_TARBALL}.tar.xz" ]]; then ls -ls ${RELEASE_TARBALL}.tar.xz; exit 0; fi
+TARBALL_OUTPUT="output/tarball"
+if [[ -f "${TARBALL_OUTPUT}/${RELEASE_TARBALL}.tar.xz" ]]; then ls -ls ${TARBALL_OUTPUT}/${RELEASE_TARBALL}.tar.xz; exit 0; fi
 CAP_DISTRO=`echo "${DISTRO}" | sed -e "s/\b\(.\)/\u\1/g"`
 CAP_RELEASE=`echo "${DISTRO_VERSION}" | sed -e "s/\b\(.\)/\u\1/g"`
 echo -e "Distribution: ${CAP_DISTRO} ${CAP_RELEASE}"
@@ -87,5 +88,12 @@ if [[ -d "${P_VALUE}" ]]; then umount ${P_VALUE}; fi
 sleep .50
 rm -fdr ${P_VALUE}
 if [[ -v "SPOOF_SCRIPT" && "$SPOOF_SCRIPT" == "true" ]]; then rm -f ${DEBOOTSTRAP_DIR}/${DISTRO_VERSION}; fi
-
+if [[ -f "${RELEASE_TARBALL}.tar.xz" ]]; then
+	mkdir -p ${TARBALL_OUTPUT}
+	mv -f ${RELEASE_TARBALL}.tar.xz ${TARBALL_OUTPUT}/
+else
+	echo -e "Failed to create ${RELEASE_TARBALL}.tar.xz?"
+	exit 1
+fi
+rm -f board.txt
 exit 0
